workflows:
    android-workflow-id:
        name: Android Sample Workflow
        # .......    
        # .......
        # .......  
    ios-workflow-id:
        name: iOS Workflow
        instance_type: mac_mini_m1
        max_build_duration: 120
        integrations:
          app_store_connect: codemagic
        environment:
          ios_signing:
            distribution_type: app_store
            bundle_identifier: io.codemagic.flutteryaml
          flutter: stable
          xcode: latest # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
          cocoapods: default
